irods/irods_testing_environment

cli.py
run_federation_tests.py
run_topology_tests.py
test_utils.py

The topology and federation options were cluttering up the main test file and did not allow for as much flexibility as may be needed in the future for these types of tests which would further diverge the different code paths.

separate topology and federation testing from main test script

---

irods_config.py

Due to changes in the control plane, the result of running `hostname` on
a given host needs to be the first entry for a given host in
hosts_config.json. This may not be required in the future, but it is for
now.

Put hostname first in hosts_config.json

---

odbc_setup.py

The '.' to indicate a file extension is not necessary when copying an
archive into the container and in fact breaks the behavior. This has
been removed so that local odbc drivers can be used.

Fix odbc driver usage in archive module

---

projects/centos-7/Dockerfile

The univMSSInterface script used in the iRODS test suite requires this
in order to properly execute the commands therein.
Requires a rebuild of the Centos-based projects for existing users.

Install which on Centos base image

---

run_plugin_tests.py

When the tests failed and --extra-logs-path was used, there was an
exception reported during the handling of another exception, muddling
the messages reported by` run_plugin_tests.py`.   This condenses the spooling of
errors from the script quite a bit and is more user friendly for that case.

[30] make errors less confusing [4-2-stable]

---

federate.py
irods_testing_environment/federate.py
irods_testing_environment/irods_setup.py
irods_testing_environment/services.py
irods_testing_environment/ssl.py
irods_testing_environment/test_utils.py
run_core_tests.py

The usage for `run_core_tests.py` has not changed, just added a new option and parallel-ized all the innards

[#29] Add parallel core test runner (main)

---

cli.py
irods_testing_environment/context.py
irods_testing_environment/test_manager.py
irods_testing_environment/test_runner.py
irods_testing_environment/test_utils.py
run_core_tests.py
run_federation_tests.py
run_plugin_tests.py
run_topology_tests.py
run_unit_tests.py

Depends on the unit tests getting packaged with `irods-server` and installed in `$IRODS_HOME/unit_tests` (see irods/irods#6164)
Encapsulated the test running context into a `test_manager` which has a collection of `test_runners` to which it distributes to-be-executed tests.

[#28] Add unit test runner (main)

---

federate.py
irods_testing_environment/services.py
run_federation_tests.py
run_plugin_tests.py

This step results in a rebuild of the image to be run if the
Dockerfile dependency has changed.  Note, this can happen due
to a switch between git branches.

[_50] request build() before up() in project (4-2-stable)

---

federate.py
irods_testing_environment/services.py
run_federation_tests.py
run_plugin_tests.py

This step results in a rebuild of the image to be run if the
Dockerfile dependency has changed.  Note, this can happen due
to a switch between git branches.

[_50] request build() before up() in project (main)

---

irods_testing_environment/container_info.py
irods_testing_environment/install/install.py
irods_testing_environment/irods_setup.py
irods_testing_environment/services.py
irods_testing_environment/test_manager.py
irods_testing_environment/test_runner.py
irods_testing_environment/test_utils.py
projects/centos-7/Dockerfile
run_core_tests.py
run_plugin_tests.py

Requires that test hooks have a `--skip-setup` and `--test` option so that we don't install the packages and stand up services repeatedly and so that test cases can be distributed among concurrent test executors.

Add parallel support to plugin test runner

---

irods_testing_environment/test_manager.py
irods_testing_environment/test_runner.py
irods_testing_environment/test_utils.py

Still trying this out, but this will allow for plugin test hooks to fall back to the "default" behavior should no `--tests` option be used with the `run_plugin_tests.py` script.

Allow for empty tests list with plugin runner and running the same test repeatedly

---

irods_testing_environment/irods_config.py
irods_testing_environment/irods_setup.py

`irods_version` was added as a required parameter and do not have a default on purpose.
Verified the following (did not run entire test suite):
- Core tests launch correctly for main
- Topology tests launch correctly for main

Setup handles changes for 4.3.0

---

irods_testing_environment/odbc_setup.py
projects/almalinux-8/almalinux-8-mysql-8/docker-compose.yml
projects/debian-11/debian-11-mysql-8/docker-compose.yml

Adapted from changes in fd736731fb5f3a23c1409305b96a6e3087d307a8
Added MySQL 5.7 and 8.0 support for debian:11 and almalinux:8.
---
I've only confirmed MySQL 8.0 on debian:11, to be honest. I suspect @korydraughn has a branch with MySQL 5.7 for almalinux:8, so maybe he will have a better take on this.

[#49] Add MySQL support for new platforms

---

projects/almalinux-8/Dockerfile
projects/almalinux-8/almalinux-8-mysql-5.7/docker-compose.yml
projects/almalinux-8/almalinux-8-mysql-8/docker-compose.yml
projects/almalinux-8/almalinux-8-postgres-10.12/docker-compose.yml
projects/centos-7/Dockerfile
projects/centos-7/centos-7-mysql-5.7/docker-compose.yml
projects/centos-7/centos-7-postgres-10.12/docker-compose.yml
projects/debian-11/Dockerfile
projects/debian-11/debian-11-mysql-5.7/docker-compose.yml
projects/debian-11/debian-11-mysql-8/docker-compose.yml
projects/debian-11/debian-11-postgres-10.12/docker-compose.yml
projects/ubuntu-18.04/Dockerfile
projects/ubuntu-18.04/ubuntu-18.04-mysql-5.7/docker-compose.yml
projects/ubuntu-18.04/ubuntu-18.04-postgres-10.12/docker-compose.yml
projects/ubuntu-20.04/Dockerfile
projects/ubuntu-20.04/ubuntu-20.04-mysql-5.7/docker-compose.yml
projects/ubuntu-20.04/ubuntu-20.04-mysql-8.0/docker-compose.yml
projects/ubuntu-20.04/ubuntu-20.04-postgres-10.12/docker-compose.yml

All of the OS's for postgres and mysql versions were testing.
I also removed the following at Alan's request:
- ubuntu-20.04 / mysql-5.7
The shared_volume change creates a volume called "shared_volume" and each container mounts this to /irods_testing_environment_mount_dir.

[irods/irods#4421] Added ability to mount a common volume

---

irods_testing_environment/logs.py
irods_testing_environment/test_manager.py
irods_testing_environment/test_runner.py

irods_testing_environment.test_manager now uses queue.Queue to manage the test list. Instead of evenly dealing out tests at the start of a run to each test_runner, the test_manager now adds the test list to a Queue and passes the Queue to the test_runner.run. The test_runners get tests from the Queue and runs them until there are no more tests in the queue.

[#96] Use queue.Queue to manage test list

---

federate.py

Turns out, `configure_ssl_in_zone` will do just that. We should probably introduce more precision controls around that, but this at least gives us the option to enable SSL in the federated environments

[#10] Add SSL support to federation setup

---

cli.py
irods_testing_environment/database_setup.py
irods_testing_environment/irods_config.py
run_core_tests.py
run_federation_tests.py
run_topology_tests.py
run_unit_tests.py

Addresses #143 
Addresses #144 
Decided that just printing sha after the whole test run is probably best for now (rather than for each executor). If the need arises in the future, we can do something like that.

Print iRODS sha/version and move database service check

---

irods_testing_environment/context.py
irods_testing_environment/irods_setup.py
irods_testing_environment/test_manager.py
irods_testing_environment/test_runner.py
irods_testing_environment/test_utils.py
projects/centos-7/Dockerfile
projects/centos-7/release.Dockerfile
projects/debian-11/Dockerfile
projects/debian-11/release.Dockerfile
projects/rockylinux-8/Dockerfile
projects/rockylinux-8/release.Dockerfile
projects/ubuntu-18.04/Dockerfile
projects/ubuntu-18.04/release.Dockerfile
projects/ubuntu-20.04/Dockerfile
projects/ubuntu-20.04/release.Dockerfile
run_core_tests.py
run_federation_tests.py
run_topology_tests.py

Addresses #52 
Addresses #156 
Supersedes #157
It seems to work, although topology tests fail pretty frequently when running with `--concurrent-test-executor-count 4` (I'm guessing because this spawns 20 containers). On the plus side, might be a good way to more reliably reproduce errors seen with sporadic test failures recently.
Still need to test with a plugin to make sure that hasn't gone sideways. Core tests, unit tests, and federation tests are working.

Add parallel topology tests and pin unittest-xml-reporting version

---

projects/almalinux-8/Dockerfile

https://github.com/irods/irods_netcdf/issues/25 is related but this requirement may apply in a broader way whenever a plugin depends on system libraries (ie build and runtime prerequisites other than irods-externals)

enable powertools for running plugin tests on almalinux

---

irods_testing_environment/irods_setup.py

Seems like rsyslog, after being killed, may either start up again by itself, or possibly start up in a delayed manner [1].  Making multiple attempts while also checking if rsyslog has already started up seems to make do for now.
---
[1] Previous observation when I ran into this issue. Might be incorrect or irrelevant.

Make multiple attempts to startup rsyslog

---

run_plugin_tests.py

In service of #53 
Apparently this interface changed at some point and was not reflected in the plugin test runner script.

[#53] Fix running plugin tests in parallel

---

projects/rockylinux-9/Dockerfile

Fix rockylinux-9 package install issues.
It should be all spaces now.

[#203] Ensure all required packages can be found

---

irods_testing_environment/odbc_setup.py

Addresses #223
I've left a boolean at the top of `odbc_setup.py` that can be used to switch back to the MariaDB ODBC driver, to allow for easier testing when working on irods/irods#7323.
Once irods/irods#7323 is fixed, this PR should be reverted, unless it has already been superseded by #208.

[#223] Use MySQL ODBC connector 8.0.33 for MariaDB projects

---

irods_testing_environment/odbc_setup.py
projects/centos-7/centos-7-mariadb-10.6/docker-compose.yml

Linked to #217 because all Centos 7 projects will be removed in the near future.

[#217] Add centos 7 / mariadb 10.6 project
