irods/irods_testing_environment

- context.py
- irods_test_config.py
I now understand how this file is intended to be used because I read the docs like a good boy :)
> Add IP addresses to hosts_config.json

- README.md
- archive.py
- cli.py
- context.py
- database_setup.py
- execute.py
- federate.py
- install.py
- irods_config.py
- irods_setup.py
- logs.py
- run_tests.py
- services.py
- setup.py
- stand_it_up.py
Federation is not as flexible as one would hope right now, but it works. Found a bug in federation for 4.2.8+ which is not affected by this change
> Add support for federation and running test_federation

- irods_testing_environment/irods_setup.py
- irods_testing_environment/test_utils.py
- projects/ubuntu-18.04/Dockerfile
Installs python3 (and python3-pip, etc.) on base image and replaces all
calls to python with python3 in the scripts and library.
> Support main for ubuntu:18.04

- .gitignore
- federate.py
- projects/centos-7/Dockerfile
- projects/ubuntu-18.04/Dockerfile
- stand_it_up.py
I'll wait for @d-w-moore's PR before merging :)
> add support for main in centos:7 + other fixes (main)

- federate.py
- stand_it_up.py
cherry-picked from work done for #32
> Some fixes (4-2-stable)

- .gitignore
- federate.py
- irods_testing_environment/federate.py
- irods_testing_environment/irods_setup.py
- irods_testing_environment/services.py
- irods_testing_environment/ssl.py
- irods_testing_environment/test_utils.py
- run_core_tests.py
cherry-picked from work done for #40 
Also added ctags file to `.gitignore` as it is in main
> [#29] Add parallel core test runner (4-2-stable)

- cli.py
- irods_testing_environment/context.py
- irods_testing_environment/test_manager.py
- irods_testing_environment/test_runner.py
- irods_testing_environment/test_utils.py
- run_core_tests.py
- run_federation_tests.py
- run_plugin_tests.py
- run_topology_tests.py
- run_unit_tests.py
cherry-picked from work for #46
> [#28] Add unit test runner (4-2-stable)

- federate.py
- install.py
- setup.py
Confirmed that install.py and federate.py are working. setup.py does not behave as intended, so I opened #55 for that.
> [#54] Fix several scripts that fell behind (main)

- federate.py
- install.py
- setup.py
cherry-picked from work for #56
> [#54] Fix several scripts that fell behind (4-2-stable)

- irods_testing_environment/archive.py
- irods_testing_environment/execute.py
- irods_testing_environment/irods_config.py
- irods_testing_environment/logs.py
- irods_testing_environment/test_manager.py
- irods_testing_environment/test_runner.py
- irods_testing_environment/test_utils.py
- run_core_tests.py
- run_federation_tests.py
- run_unit_tests.py
cherry-picked from work done for #72
> Improve test results and log collection (4-2-stable)

- irods_testing_environment/logs.py
> [#70] Remove log collection for 4.3.0 (4-2-stable)

- irods_testing_environment/irods_config.py
irods_config.configure_irods_testing now has a step to create user
accounts which may be required for testing. At this time, only test_auth
needs this and it is only for 1 user with a static password.
---
Confirmed that `test_auth` can now run and passes.
> [#89] Configure test_auth required user

- irods_testing_environment/ssl_setup.py
In 4.3.0, the default value returned by acPreConnect is now
CS_NEG_REFUSE, which will cause an SSL-enabled client to fail in the
SSL negotiation stage. This change adds the modification of acPreConnect
in core.re as part of the SSL configuration step enacted by --use-ssl.
> [#94] Modify core.re for SSL configuration

- run_federation_tests.py
- Fixed some imports which were not updated
- Fixed usage of the iRODS package installation module
- Fixed building of arguments used to run tests
---
Confirmed working by running tests on almalinux:8
> [#10] Fix run_federation_tests.py

- README.md
- Update usage notes for standing up and running various test flavors
- Add extensive details to the type of directory structure expected by
plugin test hooks, which are used by run_plugin_tests.py
--- 
Still thinking about what else to add to this but figured I'd put it up here for viewing
> Update README for clarity and ease of use

- README.md
- run_core_tests.py
- run_federation_tests.py
- run_plugin_tests.py
- run_topology_tests.py
- run_unit_tests.py
- stand_it_up.py
And document it
---
Confirmed that this works, but, y'know, still sort of experimental. Works just fine with local docker daemon as well.
> [#103] Add ssh client support for remote execution

- irods_testing_environment/irods_setup.py
Addresses #119
Required for tests to pass on tip of main
> [#119] Add rsyslog configuration logic

- irods_testing_environment/irods_config.py
Adds a cache for iRODS zone names and versions as dicts in irods_config.py. Arguably, this could be built into the zone_info, but then we would have to change a bunch of interfaces and/or make zone information global, which could muddy the waters.
---
As suggested in the commit message, I feel like there's a better way to do this, but I'll put this up here anyway.
> [#124] Cache iRODS zone names and versions

- irods_testing_environment/archive.py
> [#128] Adding tarfile member sanitization to extractall()

- projects/almalinux-8/Dockerfile
- projects/almalinux-8/release.Dockerfile
- projects/centos-7/Dockerfile
- projects/centos-7/release.Dockerfile
- projects/debian-11/Dockerfile
- projects/debian-11/release.Dockerfile
- projects/ubuntu-18.04/Dockerfile
- projects/ubuntu-18.04/release.Dockerfile
- projects/ubuntu-20.04/Dockerfile
- projects/ubuntu-20.04/release.Dockerfile
> [#127] Replace xmlrunner with unittest-xml-reporting

- irods_testing_environment/archive.py
- irods_testing_environment/irods_config.py
- irods_testing_environment/json_utils.py
Addresses irods/irods#6693
This is required in order for `pam_password` authentication to work for Centos 7.
> [irods/irods#6693] Configure pam as described in docs

- irods_testing_environment/irods_config.py
See commit message for explanation.
> [irods/irods#6482] Creates zonehopper#<remote_zone> for federation testing

- run_topology_tests.py
Running topology tests on consumer now works. Oops
> [#159] Fix service instances for topology tests on consumers

- irods_testing_environment/odbc_setup.py
- projects/ubuntu-20.04/ubuntu-20.04-postgres-14.8/docker-compose.yml
We need postgres 14 to use Debian 12
> Add support for postgres 14.3

- README.md
- irods_testing_environment/odbc_setup.py
- projects/ubuntu-22.04/Dockerfile
- projects/ubuntu-22.04/ubuntu-22.04-mysql-8.0/docker-compose.yml
- projects/ubuntu-22.04/ubuntu-22.04-postgres-14.8/docker-compose.yml
I don't remember if this works all the way, but putting up for interested eyeballs :)
---
Companion PRs:
https://github.com/irods/irods/pull/6620
https://github.com/irods/irods_client_icommands/pull/323
https://github.com/irods/irods_development_environment/pull/72
> [irods/irods#6597] Add Ubuntu 22.04 support

- README.md
- irods_testing_environment/odbc_setup.py
- projects/debian-12/Dockerfile
- projects/debian-12/debian-12-mysql-8/docker-compose.yml
- projects/debian-12/debian-12-postgres-14.8/docker-compose.yml
- projects/debian-12/release.Dockerfile
In service of irods/irods#7266
Running tests soon...
> [irods/irods#7266] Add Debian 12 support

- README.md
- irods_testing_environment/odbc_setup.py
- projects/rockylinux-9/Dockerfile
- projects/rockylinux-9/release.Dockerfile
- projects/rockylinux-9/rockylinux-9-mysql-8/docker-compose.yml
- projects/rockylinux-9/rockylinux-9-postgres-14.8/docker-compose.yml
- projects/rockylinux-9/rsyslog.conf
- projects/rockylinux-9/rsyslog.conf.default
In service of irods/irods#7191
Copied from files for rockylinux:8. Unit tests pass, core tests are running (and passing, so far). Need to try out mysql
Same caveats apply here regarding irods/irods#7349
> [irods/irods#7191] Add Rocky Linux 9 support

- run_topology_tests.py
In service of irods/irods#7000
> [irods/irods#7000] Fix consumer hostnames in run_topology_tests.py

- irods_testing_environment/logs.py
> [#186] Fix log collecting for iRODS versions >4.3

- irods_testing_environment/irods_config.py
- projects/debian-11/Dockerfile
Addresses #188 
Addresses #189
> Address some small issues

- projects/centos-7/Dockerfile
> [#195] add centos-release-scl to centos7 image

- irods_testing_environment/services.py
> [#198] Don't default construct Repo object

- irods_testing_environment/odbc_setup.py
- projects/ubuntu-24.04/Dockerfile
- projects/ubuntu-24.04/ubuntu-24.04-mysql-8/docker-compose.yml
- projects/ubuntu-24.04/ubuntu-24.04-postgres-14.8/docker-compose.yml
In service of irods/irods#7592
Companion PRs:
- irods/irods#7733
- irods/irods#7739
- irods/irods_client_icommands#477
- irods/irods_client_icommands#478
- irods/externals#246
- irods/irods_development_environment#137
> [irods/irods#7592] add ubuntu 24.04 projects

- README.md
- irods_testing_environment/odbc_setup.py
- projects/almalinux-8/almalinux-8-mysql-8.0/docker-compose.yml
- projects/almalinux-8/almalinux-8-mysql-8.4/docker-compose.yml
- projects/centos-7/centos-7-mysql-8.0/docker-compose.yml
- projects/debian-11/debian-11-mysql-8.0/docker-compose.yml
- projects/debian-12/debian-12-mysql-8.0/docker-compose.yml
- projects/debian-12/debian-12-mysql-8.4/docker-compose.yml
- projects/rockylinux-8/rockylinux-8-mysql-8.0/docker-compose.yml
- projects/rockylinux-8/rockylinux-8-mysql-8.4/docker-compose.yml
- projects/rockylinux-9/rockylinux-9-mysql-8.0/docker-compose.yml
- projects/rockylinux-9/rockylinux-9-mysql-8.4/docker-compose.yml
- projects/ubuntu-20.04/ubuntu-20.04-mysql-8.0/docker-compose.yml
- projects/ubuntu-22.04/ubuntu-22.04-mysql-8.0/docker-compose.yml
- projects/ubuntu-22.04/ubuntu-22.04-mysql-8.4/docker-compose.yml
- projects/ubuntu-24.04/ubuntu-24.04-mysql-8.0/docker-compose.yml
- projects/ubuntu-24.04/ubuntu-24.04-mysql-8.4/docker-compose.yml
Addresses #215
Addresses #216
In service of irods/irods#7592
The new 8.4 projects may not be useful until irods/irods#7495 is fixed.
> [#215,#216,irods/irods#7592] Add MySQL 8.4 projects, disambiguate MySQL 8.0 projects, update MySQL 8.0 ODBC connector, add Ubuntu 24.04 to readme

- projects/centos-7/Dockerfile
- projects/centos-7/centos-7-postgres-14/docker-compose.yml
- projects/centos-7/centos-7-postgres-16/docker-compose.yml
Addresses #220
Addresses #221
Addresses irods/irods#7865
> [#220,#221,irods/irods#7865] EL7 fixes

- irods_testing_environment/irods_config.py
This was used to resolve irods/irods#7933 and irods/irods#7934.
> [#244] Configure host_resolution instead of hosts_config.json

- irods_testing_environment/irods_config.py
Will add more words to body of commit message tomorrow.
> [#247] Make iRODS server hostname the first element in the host_resolution config

- irods_testing_environment/irods_config.py
This PR allows the core tests to pass when launched from a catalog consumer server in a topology.
Creation of the `hello` script only occurs if the installation of the catalog provider contains `msiExecCmd_bin/hello.template`.
Below are the test runs showing the results.
4.3.4 with SSL:
```
2025-03-03 15:44:52,981 - setting up catalog [almalinux-8-postgres-14_catalog_1]
2025-03-03 15:44:54,579 - setting up iRODS catalog provider [almalinux-8-postgres-14_irods-catalog-provider_1]
2025-03-03 15:45:03,196 - setting up iRODS catalog consumer [almalinux-8-postgres-14_irods-catalog-consumer_1]
2025-03-03 15:45:03,207 - setting up iRODS catalog consumer [almalinux-8-postgres-14_irods-catalog-consumer_2]
2025-03-03 15:45:03,209 - setting up iRODS catalog consumer …
```
> [#249] Create `msiExecCmd_bin/hello` from template (main)

- irods_testing_environment/tls_setup.py
- run_core_tests.py
- run_federation_tests.py
- run_topology_tests.py
Companion PR at irods/irods#8357.
> Fix passing of TLS option to run_tests.py / Update TLS config stanzas for iRODS 5 servers

- irods_testing_environment/container_info.py
> [#260] Return 'python3' for container_info.python

- irods_testing_environment/irods_setup.py
> [#262] Always configure syslog for iRODS setup

- README.md
- projects/rockylinux-8/Dockerfile
- projects/rockylinux-8/release.Dockerfile
- projects/rockylinux-9/Dockerfile
- projects/rockylinux-9/release.Dockerfile
In service of irods/irods#8533
> [irods/irods#8533] Use new location of Rocky Linux Docker images
